---
#
# Playbook to install the ELK stack
#

- hosts: elk
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: elasticsearch }
    - { role: fluentd, when: (logging_backend == 'fluentd') }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: nginx }
    - { role: curator, when: install_curator_tool }
    - { role: kibana }
    - { role: xpack, when: ((install_elasticsearch_xpack) or (install_kibana_xpack) or (install_logstash_xpack)) }
    - { role: firewall, when: manage_firewall }  
    - { role: instructions }
